name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - run: npm i -g pm2
    - run: npm ci
    - run: npm run build --if-present
    - run: pm2 start npm --name "Using pm2 deplyoed nextjs successfully" -- start 

